[general]
import = ["./themes/oxocarbon.toml"]

# Remove old import at the bottom of the file
[window.padding]
x = 3
y = 3

[terminal.shell]
program = "/bin/bash"

[window]
title = "terminal"
opacity = 0.95
decorations = "buttonless"

[font]
size = 11.5

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[cursor]

[mouse]
hide_when_typing = true

[keyboard]

[env]
TERM = "xterm-256color"

[terminal]
