[general]
import = ["./themes/modus-vivendi.toml"]

# Remove old import at the bottom of the file
[window.padding]
x = 3
y = 3

[terminal.shell]
program = "/bin/zsh"

[window]
title = "terminal"
opacity = 1.0
decorations = "buttonless"

[font]
size = 11.5
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Light" }
bold_italic = { family = "Fira Code", style = "Medium" }

[cursor]

[mouse]
hide_when_typing = true

[keyboard]

[env]
TERM = "xterm-256color"

[terminal]
